name = "vulnlist"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

target = "javascript"

[javascript]
runtime = "deno"

[javascript.deno]
allow_net = ["www.cisa.gov:443"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
birl = ">= 1.6.1 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_fetch = ">= 1.0.0 and < 2.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
